sudo: required

language: node_js
node_js:
  - 12.13.1

services:
  - docker

before_install:
  - docker-compose build --no-cache
  - docker-compose up --detach
  - docker-compose ps

script:
  # Wait for database and configure it
  - docker-compose run --rm gateway-service ./scripts/wait-for-it.sh database:3306
  - docker-compose exec -T gateway-database mysql -h0.0.0.0 -uroot -proot gluten < gateway/database/test.sql
  # Run tests
  - docker-compose run --rm gateway-service npm test

after_script:
  - docker-compose rm --stop --force -v
