language: node_js
node_js:
  - 12.13.1

jobs:
  include:
    - stage: "Lint"
      script:
        - npm run lint
        - npm run lint:fix
    - stage: "Sync"
      if: branch = develop AND type != pull_request
      script:
        - git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.fdmci.hva.nl/desqol/glutenserver.git
        - git push --force gitlab --all
        - git push --force gitlab --tags
