language: node_js

node_js:
  - '12.7.0'

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gluten;'
  - mysql -u root --default-character-set=utf8 gluten < database/data.sql

install:
  - cd server
  - npm uninstall typescript --no-save
  - npm ci

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: "Lint"
      script:
        - npm run lint
        - npm run lint:fix
    - stage: "Test"
      script:
        - npm test
    - stage: "Sync"
      if: branch = master
      script:
        - git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.fdmci.hva.nl/desqol/glutenserver.git
        - git push --force gitlab --all
        - git push --force gitlab --tags
