sudo: required

language: node_js
node_js:
  - 12.13.1

services:
  - docker

before_install:
  - docker-compose build --no-cache
  - docker-compose up --detach
  - docker-compose ps

script:
  - docker-compose exec gateway-service npm test

after_script:
  - docker-compose rm --stop --force -v
