language: node_js
node_js:
  - 12.13.1

services:
  - mysql
  - redis-server

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gluten;'
  - mysql -u root --default-character-set=utf8 gluten < database/dump.sql
  - cd server

jobs:
  include:
    - stage: "Lint"
      script:
        - npm run lint
        - npm run lint:fix
    - stage: "Test"
      script:
        - npm test
    - stage: "Sync"
      if: branch = master AND type != pull_request
      script:
        - git remote add gitlab https://oauth2:$GITLAB_TOKEN@gitlab.fdmci.hva.nl/desqol/glutenserver.git
        - git push --force gitlab --all
        - git push --force gitlab --tags

after_success:
  - npm run coverage
