version: '3.7'

services:
  database:
    image: mysql:5.7.28
    volumes:
      - './database/data:/var/lib/mysql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gluten
      MYSQL_USER: gluten
      MYSQL_PASSWORD: gluten

  server:
    build: ./server
    ports:
      - 3000:3000
    links:
      - database
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
