version: '3.7'

services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      target: production
    volumes:
      - './scripts:/opt'
      - '/etc/letsencrypt:/etc/letsencrypt'
    ports:
      - 80:80
      - 443:443
    networks:
      - services
    depends_on:
      - gateway-service

  portainer:
    image: portainer/portainer:1.23.0
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './portainer/data:/data'
    restart: always
    ports:
      - 8000:8000
      - 9000:9000

  gateway-database:
    image: mysql:5.7.28
    volumes:
      - './gateway/database/data:/var/lib/mysql'
      - './gateway/database/init.sql:/docker-entrypoint-initdb.d/init.sql'
    restart: always
    networks:
      - gateway-service
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gluten
      MYSQL_USER: gluten
      MYSQL_PASSWORD: gluten
  
  gateway-cache:
    image: redis:5.0.7
    volumes:
      - './gateway/cache:/data'
    restart: always
    networks:
      - gateway-service

  gateway-service:
    build: ./gateway/service
    volumes:
      - './scripts:/opt'
      - './gateway/service/logs:/usr/src/app/logs'
    networks:
      - services
      - gateway-service
    links:
      - gateway-database:database
      - gateway-cache:cache
    depends_on:
      - gateway-database
      - gateway-cache
    environment:
      MYSQL_HOST: database
      REDIS_HOST: cache

networks:
  services: {}
  gateway-service: {}
