version: '3.7'

services:
  database:
    image: mysql:5.7.28
    volumes:
      - './database/data:/var/lib/mysql'
      - './database/dump.sql:/docker-entrypoint-initdb.d/dump.sql'
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gluten
      MYSQL_USER: gluten
      MYSQL_PASSWORD: gluten
  
  cache:
    image: redis:5.0.7
    volumes:
      - './database/cache:/data'
    restart: always
    ports:
      - 6379:6379

  server:
    build: ./server
    volumes:
      - './server/logs:/usr/src/app/logs'
    ports:
      - 80:80
      - 443:443
    links:
      - database
      - cache
    depends_on:
      - database
      - cache
    environment:
      MYSQL_HOST: database
      REDIS_HOST: cache
