openapi: '3.0.0'

info:
  version: 1.0.0
  title: Swagger Gluten Server
  description: Gluten API in the OpenAPI 3.0 specification

servers:
  - url: /v1/

paths:
  /users:
    get:
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /products:
    description: endpoints for products
    summary: endpoints for products
  /recipes:
    description: endpoints for recipes
    summary: endpoints for recipes

components:
  schemas:
    ArrayOfUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: integer
          description: The user ID.
        firstname:
          type: string
          description: The firstname of the user.
        lastname:
          type: string
          description: The lastname of the user.
        age:
          type: integer
          description: The age of the user.
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
