openapi: 3.0.2

info:
  title: GlutenServer API spec
  version: 0.0.1

servers:
  - url: http://localhost/v1/

security:
  # Either key can be used (as in logical OR)
  - ApiKeyAuth: []
  - ApiKeyQueryAuth:  []

paths:
  /users:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'
        '401':
          $ref: "#/components/responses/UnauthorizedError"

components:
  # Reusable schemas (data models)
  schemas:
    ArrayOfUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
  
  # Security scheme definitions (see Authentication)
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
    ApiKeyQueryAuth:
      type: apiKey
      in: query
      name: api_key

  # Reusable responses, such as 401 Unauthorized or 400 Bad Request
  responses:
    UnauthorizedError:
      description: API key is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string
