openapi: 3.0.2

info:
  title: GlutenServer API spec
  version: 0.0.1

servers:
  - url: http://localhost/v1/

paths:
  /users:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfUsers'

components:
  # Reusable schemas (data models)
  schemas:
    ArrayOfUsers:
      type: array
      items:
        $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
